awejfilist = [1,2,3]
age_distribution =  ('Universe:  TOTAL POPULATION: Male; Under 5 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 5 to 9 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 10 to 14 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 15 to 17 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 18 and 19 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 20 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 21 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 22 to 24 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 25 to 29 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 30 to 34 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 35 to 39 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 40 to 44 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 45 to 49 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 50 to 54 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 55 to 59 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 60 and 61 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 62 to 64 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 65 and 66 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 67 to 69 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 70 to 74 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 75 to 79 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 80 to 84 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 85 years and over (Estimate)',
                'Universe:  TOTAL POPULATION: Female; Under 5 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 5 to 9 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 10 to 14 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 15 to 17 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 18 and 19 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 20 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 21 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 22 to 24 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 25 to 29 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 30 to 34 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 35 to 39 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 40 to 44 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 45 to 49 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 50 to 54 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 55 to 59 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 60 and 61 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 62 to 64 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 65 and 66 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 67 to 69 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 70 to 74 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 75 to 79 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 80 to 84 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 85 years and over (Estimate)')

race_distribution = ('Universe:  TOTAL POPULATION: White alone (Estimate)',
 'Universe:  TOTAL POPULATION: Black or African American alone (Estimate)',
 'Universe:  TOTAL POPULATION: American Indian and Alaska Native alone (Estimate)',
 'Universe:  TOTAL POPULATION: Asian alone (Estimate)',
 'Universe:  TOTAL POPULATION: Native Hawaiian and Other Pacific Islander alone (Estimate)',
 'Universe:  TOTAL POPULATION: Some other race alone (Estimate)',
 'Universe:  TOTAL POPULATION: Two or more races (Estimate)')

race_distribution_moe = ('Universe:  TOTAL POPULATION: White alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Black or African American alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: American Indian and Alaska Native alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Asian alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Native Hawaiian and Other Pacific Islander alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Some other race alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Two or more races(Margin of Error (+/-))')

educational_attainment_18plus = ("Universe:  POPULATION 18 YEARS AND OVER: Total (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Total(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Graduate or professional degree(Margin of Error (+/-))")
