age_distribution =  ('Universe:  TOTAL POPULATION: Male; Under 5 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 5 to 9 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 10 to 14 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 15 to 17 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 18 and 19 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 20 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 21 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 22 to 24 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 25 to 29 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 30 to 34 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 35 to 39 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 40 to 44 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 45 to 49 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 50 to 54 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 55 to 59 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 60 and 61 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 62 to 64 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 65 and 66 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 67 to 69 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 70 to 74 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 75 to 79 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 80 to 84 years (Estimate)',
                'Universe:  TOTAL POPULATION: Male; 85 years and over (Estimate)',
                'Universe:  TOTAL POPULATION: Female; Under 5 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 5 to 9 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 10 to 14 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 15 to 17 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 18 and 19 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 20 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 21 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 22 to 24 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 25 to 29 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 30 to 34 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 35 to 39 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 40 to 44 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 45 to 49 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 50 to 54 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 55 to 59 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 60 and 61 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 62 to 64 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 65 and 66 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 67 to 69 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 70 to 74 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 75 to 79 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 80 to 84 years (Estimate)',
                'Universe:  TOTAL POPULATION: Female; 85 years and over (Estimate)')

race_distribution = ('Universe:  TOTAL POPULATION: White alone (Estimate)',
 'Universe:  TOTAL POPULATION: Black or African American alone (Estimate)',
 'Universe:  TOTAL POPULATION: American Indian and Alaska Native alone (Estimate)',
 'Universe:  TOTAL POPULATION: Asian alone (Estimate)',
 'Universe:  TOTAL POPULATION: Native Hawaiian and Other Pacific Islander alone (Estimate)',
 'Universe:  TOTAL POPULATION: Some other race alone (Estimate)',
 'Universe:  TOTAL POPULATION: Two or more races (Estimate)')

race_distribution_moe = ('Universe:  TOTAL POPULATION: White alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Black or African American alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: American Indian and Alaska Native alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Asian alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Native Hawaiian and Other Pacific Islander alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Some other race alone(Margin of Error (+/-))',
'Universe:  TOTAL POPULATION: Two or more races(Margin of Error (+/-))')

educational_attainment_18plus = ("Universe:  POPULATION 18 YEARS AND OVER: Total (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Total(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 18 to 24 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 25 to 34 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 35 to 44 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 45 to 64 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Male; 65 years and over; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 18 to 24 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 25 to 34 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 35 to 44 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 45 to 64 years; Graduate or professional degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Less than 9th grade (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Less than 9th grade(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; 9th to 12th grade, no diploma (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; 9th to 12th grade, no diploma(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; High school graduate, GED, or alternative (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; High school graduate, GED, or alternative(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Some college, no degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Some college, no degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Associate's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Associate's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Bachelor's degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Bachelor's degree(Margin of Error (+/-))",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Graduate or professional degree (Estimate)",
  "Universe:  POPULATION 18 YEARS AND OVER: Female; 65 years and over; Graduate or professional degree(Margin of Error (+/-))")


veteran_status = ("Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Total (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Total(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 18 to 34 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 35 to 54 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 55 to 64 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 65 to 74 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Male; 75 years and over; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 18 to 34 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 35 to 54 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 55 to 64 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 65 to 74 years; Nonveteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over; Veteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over; Veteran(Margin of Error (+/-))",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over; Nonveteran (Estimate)",
  "Universe:  CIVILIAN POPULATION 18 YEARS AND OVER: Female; 75 years and over; Nonveteran(Margin of Error (+/-))")

household_size = ("Universe:  OCCUPIED HOUSING UNITS: Total (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Total(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 1-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 1-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 2-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 2-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 3-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 3-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 4-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 4-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 5-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 5-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 6-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 6-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 7-or-more person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Owner occupied; 7-or-more person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 1-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 1-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 2-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 2-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 3-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 3-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 4-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 4-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 5-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 5-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 6-person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 6-person household(Margin of Error (+/-))",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 7-or-more person household (Estimate)",
  "Universe:  OCCUPIED HOUSING UNITS: Renter occupied; 7-or-more person household(Margin of Error (+/-))")


#language_at_home = ("Universe:  POPULATION 5 YEARS AND OVER: Total (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: Total(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak only English (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak only English(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak Spanish (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak Spanish(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak other Indo-European languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak other Indo-European languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak Asian and Pacific Island languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak Asian and Pacific Island languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak other languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 5 to 17 years; Speak other languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak only English (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak only English(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak Spanish (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak Spanish(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak other Indo-European languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak other Indo-European languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak Asian and Pacific Island languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak Asian and Pacific Island languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak other languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 18 to 64 years; Speak other languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak only English (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak only English(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak Spanish (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak Spanish(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak other Indo-European languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak other Indo-European languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak Asian and Pacific Island languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak Asian and Pacific Island languages(Margin of Error (+/-))",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak other languages (Estimate)",
#  "Universe:  POPULATION 5 YEARS AND OVER: 65 years and over; Speak other languages(Margin of Error (+/-))")
#

school_enrollment = ("Universe:  POPULATION 3 YEARS AND OVER: Total (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Total(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in public school; 35 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Enrolled in private school; 35 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Male; Not enrolled in school; 35 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in public school; 35 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Enrolled in private school; 35 years and over(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 3 and 4 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 3 and 4 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 5 to 9 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 5 to 9 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 10 to 14 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 10 to 14 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 15 to 17 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 15 to 17 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 18 and 19 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 18 and 19 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 20 to 24 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 20 to 24 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 25 to 34 years (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 25 to 34 years(Margin of Error (+/-))",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 35 years and over (Estimate)",
  "Universe:  POPULATION 3 YEARS AND OVER: Female; Not enrolled in school; 35 years and over(Margin of Error (+/-))")

language_spoken_at_home = ("B16001_1_EST","B16001_2_EST","B16001_3_EST","B16001_6_EST","B16001_9_EST","B16001_12_EST","B16001_15_EST","B16001_18_EST","B16001_21_EST","B16001_24_EST","B16001_27_EST","B16001_30_EST","B16001_33_EST","B16001_36_EST","B16001_39_EST","B16001_42_EST","B16001_45_EST","B16001_48_EST","B16001_51_EST","B16001_54_EST","B16001_57_EST","B16001_60_EST","B16001_63_EST","B16001_66_EST","B16001_69_EST","B16001_72_EST","B16001_75_EST","B16001_78_EST","B16001_81_EST","B16001_84_EST","B16001_87_EST","B16001_90_EST","B16001_93_EST","B16001_96_EST","B16001_99_EST","B16001_102_EST","B16001_105_EST","B16001_108_EST","B16001_111_EST","B16001_114_EST","B16001_117_EST")
